const ELEMENT_TYPES = {
  text: {
    name: "Texto",
    type: "text",
    defaultValue: {
      text: "",
      x: 0,
      y: 0,
      width: 200,

      fontSize: 90,
      lineHeight: 1.4,
      bold: 400,
      boldValue: 600,

      italic: false,
      justify: false,
      uppercase: false,

      underline: false,
      list: false,
      listSymbol: "",

      textAlign: "left",
      fontFamily: "sans-serif",

      color: "#000000",
      borderWidth: 0,
      borderColor: "#000000",
      shadow: "",
      opacity: 1,

      rotation: 0,
    },
  },
  rect: {
    name: "Rectángulo",
    type: "rect",
    defaultValue: {
      x: 0,
      y: 0,
      width: 100,
      height: 100,
      color: "#000",
      borderColor: "#FFFFFF",
      borderWidth: 0,
      radius: 0,
      pattern: null,
      opacity: 1,
      shadow: "",
    },
  },
  image: {
    name: "Imagen",
    type: "image",
    defaultValue: {
      idImage: "",
      name: "",
      url: "",
      x: 0,
      y: 0,
      scale: 1,
      opacity: 1,
      crop: false,
      show_crop: false,
      x_crop: 0,
      y_crop: 0,
      width_crop: 300,
      height_crop: 300,
      blur: 0,
      shadow: "",
    },
  },
  circle: {
    name: "Círculo",
    type: "circle",
    defaultValue: {
      x: 0,
      y: 0,
      color: "#000",
      borderColor: "#FFF",
      borderWidth: 0,
      radius: 20,
      opacity: 1,
      shadow: "",
    },
  },
  polygon: {
    name: "Polígono",
    type: "polygon",
    defaultValue: {
      sides: 6,
      x: 0,
      y: 0,
      size: 20,
      color: "#000",
      borderColor: "#000",
      borderWidth: 0,
      rotation: 0,
      opacity: 1,
      shadow: "",
    },
  },
  star: {
    name: "Estrella",
    type: "star",
    defaultValue: {
      sides: 6,
      x: 0,
      y: 0,
      radius: 50,
      radius2: 25,
      color: "#000",
      borderColor: "#000",
      borderWidth: 0,
      rotation: 0,
      opacity: 1,
      shadow: "",
    },
  },
};

export default ELEMENT_TYPES;
