export const exampleList = [
  {
    id: "147",
    visible: true,
    type: "rect",
    x: 100,
    y: 400,
    width: 260,
    height: 200,
    color: "#FF0000",
    borderColor: "#FFFF00",
    borderWidth: 3,
    radius: 20,
    opacity: 1,
    shadow: "",
  },
  {
    id: "148",
    visible: true,
    type: "image",
    x: 0,
    y: 0,
    name: "vantage",
    url: "https://cf.geekdo-images.com/M0e9l-SHH2H4RMSAcnsDgg__imagepage/img/Hb7vn1MD5dk3_PMzy4MAuX9nONI=/fit-in/900x600/filters:no_upscale():strip_icc()/pic8658546.jpg",
    scale: 1,
    opacity: 1,
  },

  {
    id: "152",
    visible: true,
    type: "star",
    x: 700,
    y: 800,
    sides: 6,
    radius: 80,
    radius2: 32,
    color: "#2299ff",
    borderColor: "#FFFFFF",
    borderWidth: 6,
    rotation: 20,
    opacity: 1,
    shadow: "",
  },
];
