export const bruss = {
  name: "Bruss",
  elementList: [
    {
      id: "bce9abde-e848-4c73-b10a-083cf4e08ccb",
      type: "image",
      youtube: {
        idImage: "cc9a1a1e-0681-435d-84eb-5c091602b696",
        name: "bg",
        url: "http://res.cloudinary.com/cazu/image/upload/v1755186903/xvid289ec3ztix5ffgkg.png",
        x: 0,
        y: 0,
        scale: 0.49,
        opacity: 1,
        crop: false,
        show_crop: false,
        x_crop: 0,
        y_crop: 0,
        width_crop: 300,
        height_crop: 300,
        blur: 0,
        shadow: "",
        visible: true,
      },
      instagram: {
        idImage: "cc9a1a1e-0681-435d-84eb-5c091602b696",
        name: "bg",
        url: "http://res.cloudinary.com/cazu/image/upload/v1755186903/xvid289ec3ztix5ffgkg.png",
        x: 0,
        y: 0,
        scale: 0.49,
        opacity: 1,
        crop: false,
        show_crop: false,
        x_crop: 0,
        y_crop: 0,
        width_crop: 300,
        height_crop: 300,
        blur: 0,
        shadow: "",
        visible: true,
      },
    },
    {
      id: "5d7bc67c-c2f8-448c-b35a-d9d751a6bc87",
      type: "image",
      youtube: {
        name: "ace",
        idImage: "9069519a-7411-42cc-bc83-97766c5d1966",
        url: "http://res.cloudinary.com/cazu/image/upload/v1764681713/h0xjgczdfnjqv4prk6rj.jpg",
        x: 0,
        y: 35,
        scale: 0.8,
        opacity: 0.9,
        crop: true,
        show_crop: false,
        x_crop: 0,
        y_crop: 220,
        width_crop: 640,
        height_crop: 1000,
        blur: 0,
        shadow: "-5 0 25 #000",
        visible: true,
      },
      instagram: {
        name: "ace",
        idImage: "d4651a9d-858e-4b7c-89f9-f2a3fede1887",
        url: "https://cf.geekdo-images.com/m6Do-APgKAZXZvH5UaWoCQ__original/img/t3P7L-OkowaeMUbgLy5b66wkwBg=/0x0/filters:format(jpeg)/pic8773199.jpg",
        x: 0,
        y: 14,
        scale: 1.7,
        opacity: 0.7,
        crop: false,
        show_crop: false,
        x_crop: -300,
        y_crop: -260,
        width_crop: 332,
        height_crop: 970,
        blur: 0,
        shadow: "-5 0 25 #000",
        visible: true,
      },
    },
    {
      id: "e7323720-d9f3-42f6-ad0f-98298f523627",
      type: "image",
      youtube: {
        idImage: "d5053f2c-cea4-486b-8d3a-e14a04aa057b",
        name: "polis",
        url: "https://cf.geekdo-images.com/08V8nzzLAr190Miv9GeitA__original/img/7gRe3HqaZPZPLNyKiBaq0EMbhU8=/0x0/filters:format(png)/pic2083738.png",
        x: 510,
        y: 35,
        scale: 1.55,
        opacity: 0.5,
        crop: true,
        show_crop: false,
        x_crop: -20,
        y_crop: 0,
        width_crop: 2000,
        height_crop: 1000,
        blur: 4,
        shadow: "-5 0 25 #000",
        visible: true,
      },
      instagram: {
        idImage: "3447bdf3-14cf-4437-8c80-a9c5ca462328",
        name: "polis",
        url: "https://cf.geekdo-images.com/sR9vKUFfimiNWW7dOSkBMg__original/img/RNYk3JfdCaMmsTGatAqn5onZPBs=/0x0/filters:format(jpeg)/pic5264401.jpg",
        x: 333,
        y: 14,
        scale: 0.75,
        opacity: 1,
        crop: true,
        show_crop: false,
        x_crop: -100,
        y_crop: -294,
        width_crop: 333,
        height_crop: 969,
        blur: 3,
        shadow: "-5 0 25 #000",
        visible: true,
      },
    },
    {
      id: "6535736d-0a60-48ae-9587-451e8c038fe2",
      type: "rect",
      youtube: {
        x: 0,
        y: 34,
        width: 1920,
        height: 7,
        color: "#000",
        borderColor: "#FFFFFF",
        borderWidth: 0,
        radius: 0,
        pattern: null,
        opacity: 1,
        shadow: "",
        visible: true,
      },
      instagram: {
        x: 0,
        y: 14,
        width: 1920,
        height: 7,
        color: "#000",
        borderColor: "#FFFFFF",
        borderWidth: 0,
        radius: 0,
        pattern: null,
        opacity: 1,
        shadow: "",
        visible: true,
      },
    },
    {
      id: "6c116b69-6e4a-44ae-96ca-e20d69332f77",
      type: "rect",
      youtube: {
        x: 0,
        y: 1028,
        width: 1920,
        height: 10,
        color: "#000",
        borderColor: "#FFFFFF",
        borderWidth: 0,
        radius: 0,
        pattern: null,
        opacity: 1,
        shadow: "",
        visible: true,
      },
      instagram: {
        x: 0,
        y: 976,
        width: 1920,
        height: 10,
        color: "#000",
        borderColor: "#FFFFFF",
        borderWidth: 0,
        radius: 0,
        pattern: null,
        opacity: 1,
        shadow: "",
        visible: true,
      },
    },
    {
      id: "261493ed-1829-49f6-90a7-dbf50b6b620f",
      type: "rect",
      youtube: {
        x: 0,
        y: 36,
        width: 1920,
        height: 217,
        color: "#000",
        borderColor: "#FFFFFF",
        borderWidth: 0,
        radius: 0,
        pattern: null,
        opacity: 0.55,
        shadow: "",
        visible: true,
      },
      instagram: {
        x: 0,
        y: 16,
        width: 1000,
        height: 169,
        color: "#000",
        borderColor: "#FFFFFF",
        borderWidth: 0,
        radius: 0,
        pattern: null,
        opacity: 0.5,
        shadow: "",
        visible: true,
      },
    },
    {
      id: "5925d7bf-6578-4a2a-b154-2089ffd67780",
      type: "rect",
      youtube: {
        x: 0,
        y: 634,
        width: 1920,
        height: 400,
        color: "#000",
        borderColor: "#FFFFFF",
        borderWidth: 0,
        radius: 0,
        pattern: null,
        opacity: 0.2,
        shadow: "",
        visible: false,
      },
      instagram: {
        x: 0,
        y: 506,
        width: 1920,
        height: 400,
        color: "#000",
        borderColor: "#FFFFFF",
        borderWidth: 0,
        radius: 0,
        pattern: null,
        opacity: 0.4,
        shadow: "",
        visible: true,
      },
    },
    {
      id: "3b781cdf-d7c8-4bdb-98ce-5a59184deb78",
      type: "image",
      youtube: {
        idImage: "6019e6b1-edfe-4afe-9a25-9bbe8b1eb919",
        name: "rueda",
        url: "http://res.cloudinary.com/cazu/image/upload/v1755188148/uc3u4tcwmchwslo6ylno.png",
        x: 1300,
        y: -395,
        scale: 1,
        opacity: 0.85,
        crop: false,
        show_crop: false,
        x_crop: 0,
        y_crop: 0,
        width_crop: 300,
        height_crop: 300,
        blur: 0,
        shadow: "",
        visible: true,
      },
      instagram: {
        idImage: "6019e6b1-edfe-4afe-9a25-9bbe8b1eb919",
        name: "rueda",
        url: "http://res.cloudinary.com/cazu/image/upload/v1755188148/uc3u4tcwmchwslo6ylno.png",
        x: 500,
        y: -353,
        scale: 1,
        opacity: 0.45,
        crop: false,
        show_crop: false,
        x_crop: 0,
        y_crop: 0,
        width_crop: 300,
        height_crop: 300,
        blur: 0,
        shadow: "",
        visible: true,
      },
    },
    {
      id: "92780d2c-db91-40d2-b86e-2e913ea70f63",
      type: "image",
      youtube: {
        idImage: "12b5961c-3b8f-48d7-9c18-a14b8efa227d",
        name: "rueda2",
        url: "http://res.cloudinary.com/cazu/image/upload/v1755188148/uc3u4tcwmchwslo6ylno.png",
        x: -122,
        y: 749,
        scale: 0.68,
        opacity: 0.9,
        crop: false,
        show_crop: false,
        x_crop: 0,
        y_crop: 0,
        width_crop: 300,
        height_crop: 300,
        blur: 0,
        shadow: "",
        visible: true,
      },
      instagram: {
        idImage: "12b5961c-3b8f-48d7-9c18-a14b8efa227d",
        name: "rueda2",
        url: "http://res.cloudinary.com/cazu/image/upload/v1755188148/uc3u4tcwmchwslo6ylno.png",
        x: -142,
        y: 539,
        scale: 0.68,
        opacity: 0.45,
        crop: false,
        show_crop: false,
        x_crop: 0,
        y_crop: 0,
        width_crop: 300,
        height_crop: 300,
        blur: 3,
        shadow: "",
        visible: true,
      },
    },
    {
      id: "ffaa4af5-2cb6-4793-ae04-c1d32029313e",
      type: "image",
      youtube: {
        idImage: "bb900043-6d9f-476b-bc45-30d96e18fc3d",
        name: "LA RUEDA LUDICA",
        url: "http://res.cloudinary.com/cazu/image/upload/v1755188423/nicr6kmwtsiug6i0xkos.png",
        x: 41,
        y: 56,
        scale: 1.005,
        opacity: 1,
        crop: false,
        show_crop: false,
        x_crop: 0,
        y_crop: 0,
        width_crop: 300,
        height_crop: 300,
        blur: 0,
        shadow: "",
        visible: true,
      },
      instagram: {
        idImage: "bb900043-6d9f-476b-bc45-30d96e18fc3d",
        name: "LA RUEDA LUDICA",
        url: "http://res.cloudinary.com/cazu/image/upload/v1755188423/nicr6kmwtsiug6i0xkos.png",
        x: 19,
        y: 65,
        scale: 0.55,
        opacity: 1,
        crop: false,
        show_crop: false,
        x_crop: 0,
        y_crop: 0,
        width_crop: 300,
        height_crop: 300,
        blur: 0,
        shadow: "",
        visible: true,
      },
    },
    {
      id: "04707e48-482d-4d00-bd83-0e8dbeb52b42",
      type: "text",
      youtube: {
        text: "40",
        x: 1351,
        y: 23,
        width: 700,
        fontSize: 258,
        lineHeight: 1,
        bold: 400,
        boldValue: 600,
        italic: true,
        justify: false,
        uppercase: false,
        underline: false,
        list: false,
        listSymbol: "",
        textAlign: "center",
        fontFamily: "Libre Baskerville",
        color: "#ffffff",
        borderWidth: 0,
        borderColor: "#000000",
        shadow: "0 6 20 #00000099",
        opacity: 1,
        rotation: 0,
        visible: true,
      },
      instagram: {
        text: "32",
        x: 560,
        y: 53,
        width: 700,
        fontSize: 124,
        lineHeight: 1,
        bold: 400,
        boldValue: 600,
        italic: true,
        justify: false,
        uppercase: false,
        underline: false,
        list: false,
        listSymbol: "",
        textAlign: "center",
        fontFamily: "Libre Baskerville",
        color: "#ffffff",
        borderWidth: 0,
        borderColor: "#000000",
        shadow: "0 6 20 #00000099",
        opacity: 1,
        rotation: 0,
        visible: true,
      },
    },
    {
      id: "1b9e92b4-31ce-4170-a061-9effd13aea89",
      type: "image",
      youtube: {
        idImage: "a02bc134-c322-409d-9c4f-302f634a2a3d",
        name: "",
        url: "http://res.cloudinary.com/cazu/image/upload/v1755188761/mwumr7hgt4ptx4tcwwsa.png",
        x: 1312,
        y: 23,
        scale: 0.575,
        opacity: 1,
        crop: false,
        show_crop: false,
        x_crop: 0,
        y_crop: 0,
        width_crop: 300,
        height_crop: 300,
        blur: 0,
        shadow: "",
        visible: true,
      },
      instagram: {
        idImage: "a02bc134-c322-409d-9c4f-302f634a2a3d",
        name: "",
        url: "http://res.cloudinary.com/cazu/image/upload/v1755188761/mwumr7hgt4ptx4tcwwsa.png",
        x: 720,
        y: 40,
        scale: 0.32,
        opacity: 1,
        crop: false,
        show_crop: false,
        x_crop: 0,
        y_crop: 0,
        width_crop: 300,
        height_crop: 300,
        blur: 0,
        shadow: "",
        visible: true,
      },
    },
    {
      instagram: {
        idImage: "0dadf46d-d2da-45cb-b480-38e031ad7168",
        name: "",
        url: "http://res.cloudinary.com/cazu/image/upload/v1755524866/kihfttvltpxap1abofde.png",
        x: 0,
        y: 855,
        scale: 1.035,
        opacity: 1,
        crop: false,
        show_crop: false,
        x_crop: 0,
        y_crop: 0,
        width_crop: 300,
        height_crop: 300,
        blur: 0,
        shadow: "",
        visible: true,
      },
      id: "cde3a4ff-29c1-4cac-9a9b-a34804eae8d6",
      type: "image",
      youtube: {
        idImage: "0dadf46d-d2da-45cb-b480-38e031ad7168",
        name: "",
        url: "http://res.cloudinary.com/cazu/image/upload/v1755524866/kihfttvltpxap1abofde.png",
        x: 0,
        y: 855,
        scale: 1.035,
        opacity: 1,
        crop: false,
        show_crop: false,
        x_crop: 0,
        y_crop: 0,
        width_crop: 300,
        height_crop: 300,
        blur: 0,
        shadow: "",
        visible: false,
      },
    },
    {
      id: "828a9711-871b-4d73-935c-8e796f10824a",
      type: "text",
      youtube: {
        text: "Especial",
        x: -65,
        y: 367,
        width: 1920,
        fontSize: 56,
        lineHeight: 1,
        bold: "600",
        boldValue: 600,
        italic: true,
        justify: false,
        uppercase: false,
        underline: false,
        list: false,
        listSymbol: "",
        textAlign: "right",
        fontFamily: "Libre Baskerville",
        color: "#fdff9e",
        borderWidth: 0,
        borderColor: "#000000",
        shadow: "0 6 16 #000000",
        opacity: 1,
        rotation: 0,
        visible: true,
      },
      instagram: {
        text: "Especial",
        x: -40,
        y: 591,
        width: 1000,
        fontSize: 61,
        lineHeight: 1,
        bold: "600",
        boldValue: 600,
        italic: true,
        justify: false,
        uppercase: false,
        underline: false,
        list: false,
        listSymbol: "",
        textAlign: "right",
        fontFamily: "Libre Baskerville",
        color: "#fdff9e",
        borderWidth: 0,
        borderColor: "#000000",
        shadow: "0 6 16 #000000",
        opacity: 1,
        rotation: 0,
        visible: true,
      },
    },
    {
      id: "4156935e-b76e-4170-a051-d407c1a76839",
      type: "text",
      youtube: {
        text: "Juegos de conflicto",
        x: -65,
        y: 449,
        width: 1920,
        fontSize: 117,
        lineHeight: 1,
        bold: "600",
        boldValue: 600,
        italic: false,
        justify: false,
        uppercase: false,
        underline: false,
        list: false,
        listSymbol: "",
        textAlign: "right",
        fontFamily: "Libre Baskerville",
        color: "#ffffff",
        borderWidth: 0,
        borderColor: "#000000",
        shadow: "0 6 16 #000000",
        opacity: 1,
        rotation: 0,
        visible: true,
      },
      instagram: {
        text: "Tormenta de juegos",
        x: -40,
        y: 685,
        width: 1000,
        fontSize: 80,
        lineHeight: 1,
        bold: "600",
        boldValue: 600,
        italic: false,
        justify: false,
        uppercase: false,
        underline: false,
        list: false,
        listSymbol: "",
        textAlign: "right",
        fontFamily: "Libre Baskerville",
        color: "#ffffff",
        borderWidth: 0,
        borderColor: "#000000",
        shadow: "0 6 16 #000000",
        opacity: 1,
        rotation: 0,
        visible: true,
      },
    },
    {
      id: "3bc229f3-67e4-456a-bf1b-43f193e9e382_d",
      type: "text",
      youtube: {
        text: "con Bruss Brussco",
        x: -65,
        y: 562,
        width: 1920,
        fontSize: 52,
        lineHeight: 1,
        bold: "600",
        boldValue: 600,
        italic: false,
        justify: false,
        uppercase: false,
        underline: false,
        list: false,
        listSymbol: "",
        textAlign: "right",
        fontFamily: "Libre Baskerville",
        color: "#ffffff",
        borderWidth: 0,
        borderColor: "#000000",
        shadow: "0 6 16 #000000",
        opacity: 1,
        rotation: 0,
        visible: true,
      },
      instagram: {
        text: "Tormenta de juegos",
        x: -40,
        y: 685,
        width: 1000,
        fontSize: 80,
        lineHeight: 1,
        bold: "600",
        boldValue: 600,
        italic: false,
        justify: false,
        uppercase: false,
        underline: false,
        list: false,
        listSymbol: "",
        textAlign: "right",
        fontFamily: "Libre Baskerville",
        color: "#ffffff",
        borderWidth: 0,
        borderColor: "#000000",
        shadow: "0 6 16 #000000",
        opacity: 1,
        rotation: 0,
        visible: true,
      },
    },
    {
      id: "cfd557e9-27a0-4cc6-8797-02b19f4a6861_d",
      type: "text",
      youtube: {
        text: "y se viene el",
        x: -65,
        y: 664,
        width: 1920,
        fontSize: 40,
        lineHeight: 1,
        bold: "600",
        boldValue: 600,
        italic: true,
        justify: false,
        uppercase: false,
        underline: false,
        list: false,
        listSymbol: "",
        textAlign: "right",
        fontFamily: "Libre Baskerville",
        color: "#fdff9e",
        borderWidth: 0,
        borderColor: "#000000",
        shadow: "0 6 16 #000000",
        opacity: 1,
        rotation: 0,
        visible: true,
      },
      instagram: {
        text: "Especial",
        x: -40,
        y: 591,
        width: 1000,
        fontSize: 61,
        lineHeight: 1,
        bold: "600",
        boldValue: 600,
        italic: true,
        justify: false,
        uppercase: false,
        underline: false,
        list: false,
        listSymbol: "",
        textAlign: "right",
        fontFamily: "Libre Baskerville",
        color: "#fdff9e",
        borderWidth: 0,
        borderColor: "#000000",
        shadow: "0 6 16 #000000",
        opacity: 1,
        rotation: 0,
        visible: true,
      },
    },
    {
      id: "0b7b7109-e275-4d2e-806a-b970719266c7_d",
      type: "text",
      youtube: {
        text: "Top 10 de Cazagangas",
        x: -65,
        y: 713,
        width: 1920,
        fontSize: 69,
        lineHeight: 1,
        bold: "600",
        boldValue: 600,
        italic: false,
        justify: false,
        uppercase: false,
        underline: false,
        list: false,
        listSymbol: "",
        textAlign: "right",
        fontFamily: "Libre Baskerville",
        color: "#ffffff",
        borderWidth: 0,
        borderColor: "#000000",
        shadow: "0 6 16 #000000",
        opacity: 1,
        rotation: 0,
        visible: true,
      },
      instagram: {
        text: "Tormenta de juegos",
        x: -40,
        y: 685,
        width: 1000,
        fontSize: 80,
        lineHeight: 1,
        bold: "600",
        boldValue: 600,
        italic: false,
        justify: false,
        uppercase: false,
        underline: false,
        list: false,
        listSymbol: "",
        textAlign: "right",
        fontFamily: "Libre Baskerville",
        color: "#ffffff",
        borderWidth: 0,
        borderColor: "#000000",
        shadow: "0 6 16 #000000",
        opacity: 1,
        rotation: 0,
        visible: true,
      },
    },
    {
      id: "f2149035-6a21-4a96-8eda-96f02f693f7b_d",
      type: "text",
      youtube: {
        text: "y como siempre",
        x: -65,
        y: 848,
        width: 1920,
        fontSize: 40,
        lineHeight: 1,
        bold: "600",
        boldValue: 600,
        italic: true,
        justify: false,
        uppercase: false,
        underline: false,
        list: false,
        listSymbol: "",
        textAlign: "right",
        fontFamily: "Libre Baskerville",
        color: "#fdff9e",
        borderWidth: 0,
        borderColor: "#000000",
        shadow: "0 6 16 #000000",
        opacity: 1,
        rotation: 0,
        visible: true,
      },
      instagram: {
        text: "Especial",
        x: -40,
        y: 591,
        width: 1000,
        fontSize: 61,
        lineHeight: 1,
        bold: "600",
        boldValue: 600,
        italic: true,
        justify: false,
        uppercase: false,
        underline: false,
        list: false,
        listSymbol: "",
        textAlign: "right",
        fontFamily: "Libre Baskerville",
        color: "#fdff9e",
        borderWidth: 0,
        borderColor: "#000000",
        shadow: "0 6 16 #000000",
        opacity: 1,
        rotation: 0,
        visible: true,
      },
    },
    {
      id: "bfc8defc-7cf0-42c3-9ccd-2e4121a53698_d",
      type: "text",
      youtube: {
        text: "Tormenta de juegos",
        x: -65,
        y: 905,
        width: 1920,
        fontSize: 75,
        lineHeight: 1,
        bold: "600",
        boldValue: 600,
        italic: false,
        justify: false,
        uppercase: false,
        underline: false,
        list: false,
        listSymbol: "",
        textAlign: "right",
        fontFamily: "Libre Baskerville",
        color: "#ffffff",
        borderWidth: 0,
        borderColor: "#000000",
        shadow: "0 6 16 #000000",
        opacity: 1,
        rotation: 0,
        visible: true,
      },
      instagram: {
        text: "Tormenta de juegos",
        x: -40,
        y: 685,
        width: 1000,
        fontSize: 80,
        lineHeight: 1,
        bold: "600",
        boldValue: 600,
        italic: false,
        justify: false,
        uppercase: false,
        underline: false,
        list: false,
        listSymbol: "",
        textAlign: "right",
        fontFamily: "Libre Baskerville",
        color: "#ffffff",
        borderWidth: 0,
        borderColor: "#000000",
        shadow: "0 6 16 #000000",
        opacity: 1,
        rotation: 0,
        visible: true,
      },
    },
  ],
};
