export const resena = {
  name: "Reseña",
  elementList: [
    {
      id: "bce9abde-e848-4c73-b10a-083cf4e08ccb",
      type: "image",
      youtube: {
        idImage: "cc9a1a1e-0681-435d-84eb-5c091602b696",
        name: "bg",
        url: "http://res.cloudinary.com/cazu/image/upload/v1755186903/xvid289ec3ztix5ffgkg.png",
        x: 0,
        y: 0,
        scale: 0.49,
        opacity: 1,
        crop: false,
        show_crop: false,
        x_crop: 0,
        y_crop: 0,
        width_crop: 300,
        height_crop: 300,
        blur: 0,
        shadow: "",
        visible: true,
      },
      instagram: {
        idImage: "cc9a1a1e-0681-435d-84eb-5c091602b696",
        name: "bg",
        url: "http://res.cloudinary.com/cazu/image/upload/v1755186903/xvid289ec3ztix5ffgkg.png",
        x: 0,
        y: 0,
        scale: 0.49,
        opacity: 1,
        crop: false,
        show_crop: false,
        x_crop: 0,
        y_crop: 0,
        width_crop: 300,
        height_crop: 300,
        blur: 0,
        shadow: "",
        visible: true,
      },
    },
    {
      id: "5d7bc67c-c2f8-448c-b35a-d9d751a6bc87",
      type: "image",
      youtube: {
        name: "portada",
        idImage: "2a337d2e-187a-409a-b5fd-ad1bc3d2efce",
        url: "https://cf.geekdo-images.com/Bo6QYIQWzRRcn7KyO3AIPg__original/img/eQ-YojBJLh3FFFa_Cn-bbHbs-wk=/0x0/filters:format(png)/pic8512516.png",
        x: 0,
        y: 35,
        scale: 1.605,
        opacity: 1,
        crop: true,
        show_crop: false,
        x_crop: 0,
        y_crop: -315,
        width_crop: 1920,
        height_crop: 1000,
        blur: 1,
        shadow: "-5 0 25 #000",
        visible: true,
      },
      instagram: {
        name: "ace",
        idImage: "d4651a9d-858e-4b7c-89f9-f2a3fede1887",
        url: "https://cf.geekdo-images.com/m6Do-APgKAZXZvH5UaWoCQ__original/img/t3P7L-OkowaeMUbgLy5b66wkwBg=/0x0/filters:format(jpeg)/pic8773199.jpg",
        x: 0,
        y: 14,
        scale: 1.7,
        opacity: 0.7,
        crop: false,
        show_crop: false,
        x_crop: -300,
        y_crop: -260,
        width_crop: 332,
        height_crop: 970,
        blur: 0,
        shadow: "-5 0 25 #000",
        visible: true,
      },
    },
    {
      id: "ef925bf8-198c-46b4-8cd7-aceaaf718174_d",
      type: "image",
      youtube: {
        name: "portada",
        idImage: "2a337d2e-187a-409a-b5fd-ad1bc3d2efce",
        url: "https://cf.geekdo-images.com/Bo6QYIQWzRRcn7KyO3AIPg__original/img/eQ-YojBJLh3FFFa_Cn-bbHbs-wk=/0x0/filters:format(png)/pic8512516.png",
        x: 0,
        y: 510,
        scale: 1.605,
        opacity: 0.65,
        crop: true,
        show_crop: false,
        x_crop: 0,
        y_crop: -800,
        width_crop: 1920,
        height_crop: 458,
        blur: 10,
        shadow: "-5 0 25 #000",
        visible: true,
      },
      instagram: {
        name: "ace",
        idImage: "d4651a9d-858e-4b7c-89f9-f2a3fede1887",
        url: "https://cf.geekdo-images.com/m6Do-APgKAZXZvH5UaWoCQ__original/img/t3P7L-OkowaeMUbgLy5b66wkwBg=/0x0/filters:format(jpeg)/pic8773199.jpg",
        x: 0,
        y: 14,
        scale: 1.7,
        opacity: 0.7,
        crop: false,
        show_crop: false,
        x_crop: -300,
        y_crop: -260,
        width_crop: 332,
        height_crop: 970,
        blur: 0,
        shadow: "-5 0 25 #000",
        visible: true,
      },
    },
    {
      id: "6535736d-0a60-48ae-9587-451e8c038fe2",
      type: "rect",
      youtube: {
        x: 0,
        y: 34,
        width: 1920,
        height: 7,
        color: "#000",
        borderColor: "#FFFFFF",
        borderWidth: 0,
        radius: 0,
        pattern: null,
        opacity: 1,
        shadow: "",
        visible: true,
      },
      instagram: {
        x: 0,
        y: 14,
        width: 1920,
        height: 7,
        color: "#000",
        borderColor: "#FFFFFF",
        borderWidth: 0,
        radius: 0,
        pattern: null,
        opacity: 1,
        shadow: "",
        visible: true,
      },
    },
    {
      id: "6c116b69-6e4a-44ae-96ca-e20d69332f77",
      type: "rect",
      youtube: {
        x: 0,
        y: 1028,
        width: 1920,
        height: 10,
        color: "#000",
        borderColor: "#FFFFFF",
        borderWidth: 0,
        radius: 0,
        pattern: null,
        opacity: 1,
        shadow: "",
        visible: true,
      },
      instagram: {
        x: 0,
        y: 976,
        width: 1920,
        height: 10,
        color: "#000",
        borderColor: "#FFFFFF",
        borderWidth: 0,
        radius: 0,
        pattern: null,
        opacity: 1,
        shadow: "",
        visible: true,
      },
    },
    {
      id: "3b781cdf-d7c8-4bdb-98ce-5a59184deb78",
      type: "image",
      youtube: {
        idImage: "6019e6b1-edfe-4afe-9a25-9bbe8b1eb919",
        name: "rueda",
        url: "http://res.cloudinary.com/cazu/image/upload/v1755188148/uc3u4tcwmchwslo6ylno.png",
        x: 1300,
        y: -395,
        scale: 1,
        opacity: 0.85,
        crop: false,
        show_crop: false,
        x_crop: 0,
        y_crop: 0,
        width_crop: 300,
        height_crop: 300,
        blur: 0,
        shadow: "",
        visible: true,
      },
      instagram: {
        idImage: "6019e6b1-edfe-4afe-9a25-9bbe8b1eb919",
        name: "rueda",
        url: "http://res.cloudinary.com/cazu/image/upload/v1755188148/uc3u4tcwmchwslo6ylno.png",
        x: 500,
        y: -353,
        scale: 1,
        opacity: 0.45,
        crop: false,
        show_crop: false,
        x_crop: 0,
        y_crop: 0,
        width_crop: 300,
        height_crop: 300,
        blur: 0,
        shadow: "",
        visible: true,
      },
    },
    {
      id: "92780d2c-db91-40d2-b86e-2e913ea70f63",
      type: "image",
      youtube: {
        idImage: "12b5961c-3b8f-48d7-9c18-a14b8efa227d",
        name: "rueda2",
        url: "http://res.cloudinary.com/cazu/image/upload/v1755188148/uc3u4tcwmchwslo6ylno.png",
        x: -122,
        y: 749,
        scale: 0.68,
        opacity: 0.9,
        crop: false,
        show_crop: false,
        x_crop: 0,
        y_crop: 0,
        width_crop: 300,
        height_crop: 300,
        blur: 0,
        shadow: "",
        visible: true,
      },
      instagram: {
        idImage: "12b5961c-3b8f-48d7-9c18-a14b8efa227d",
        name: "rueda2",
        url: "http://res.cloudinary.com/cazu/image/upload/v1755188148/uc3u4tcwmchwslo6ylno.png",
        x: -142,
        y: 539,
        scale: 0.68,
        opacity: 0.45,
        crop: false,
        show_crop: false,
        x_crop: 0,
        y_crop: 0,
        width_crop: 300,
        height_crop: 300,
        blur: 3,
        shadow: "",
        visible: true,
      },
    },
    {
      instagram: {
        idImage: "0dadf46d-d2da-45cb-b480-38e031ad7168",
        name: "",
        url: "http://res.cloudinary.com/cazu/image/upload/v1755524866/kihfttvltpxap1abofde.png",
        x: 0,
        y: 855,
        scale: 1.035,
        opacity: 1,
        crop: false,
        show_crop: false,
        x_crop: 0,
        y_crop: 0,
        width_crop: 300,
        height_crop: 300,
        blur: 0,
        shadow: "",
        visible: true,
      },
      id: "cde3a4ff-29c1-4cac-9a9b-a34804eae8d6",
      type: "image",
      youtube: {
        idImage: "0dadf46d-d2da-45cb-b480-38e031ad7168",
        name: "",
        url: "http://res.cloudinary.com/cazu/image/upload/v1755524866/kihfttvltpxap1abofde.png",
        x: 0,
        y: 855,
        scale: 1.035,
        opacity: 1,
        crop: false,
        show_crop: false,
        x_crop: 0,
        y_crop: 0,
        width_crop: 300,
        height_crop: 300,
        blur: 0,
        shadow: "",
        visible: false,
      },
    },
    {
      id: "828a9711-871b-4d73-935c-8e796f10824a",
      type: "text",
      youtube: {
        text: "Reseña",
        x: -65,
        y: 561,
        width: 1920,
        fontSize: 87,
        lineHeight: 1,
        bold: "600",
        boldValue: 600,
        italic: true,
        justify: false,
        uppercase: false,
        underline: false,
        list: false,
        listSymbol: "",
        textAlign: "right",
        fontFamily: "Libre Baskerville",
        color: "#fdff9e",
        borderWidth: 0,
        borderColor: "#000000",
        shadow: "0 6 16 #000000",
        opacity: 1,
        rotation: 0,
        visible: true,
      },
      instagram: {
        text: "Especial",
        x: -40,
        y: 591,
        width: 1000,
        fontSize: 61,
        lineHeight: 1,
        bold: "600",
        boldValue: 600,
        italic: true,
        justify: false,
        uppercase: false,
        underline: false,
        list: false,
        listSymbol: "",
        textAlign: "right",
        fontFamily: "Libre Baskerville",
        color: "#fdff9e",
        borderWidth: 0,
        borderColor: "#000000",
        shadow: "0 6 16 #000000",
        opacity: 1,
        rotation: 0,
        visible: true,
      },
    },
    {
      id: "4156935e-b76e-4170-a051-d407c1a76839",
      type: "text",
      youtube: {
        text: "Eternal Decks",
        x: -65,
        y: 681,
        width: 1920,
        fontSize: 180,
        lineHeight: 1,
        bold: "600",
        boldValue: 600,
        italic: false,
        justify: false,
        uppercase: false,
        underline: false,
        list: false,
        listSymbol: "",
        textAlign: "right",
        fontFamily: "Libre Baskerville",
        color: "#ffffff",
        borderWidth: 0,
        borderColor: "#000000",
        shadow: "0 6 16 #000000",
        opacity: 1,
        rotation: 0,
        visible: true,
      },
      instagram: {
        text: "Tormenta de juegos",
        x: -40,
        y: 685,
        width: 1000,
        fontSize: 80,
        lineHeight: 1,
        bold: "600",
        boldValue: 600,
        italic: false,
        justify: false,
        uppercase: false,
        underline: false,
        list: false,
        listSymbol: "",
        textAlign: "right",
        fontFamily: "Libre Baskerville",
        color: "#ffffff",
        borderWidth: 0,
        borderColor: "#000000",
        shadow: "0 6 16 #000000",
        opacity: 1,
        rotation: 0,
        visible: true,
      },
    },
    {
      id: "033c3871-974c-48cf-b3f6-e85f84349cdc_d",
      type: "text",
      youtube: {
        text: '"...destinado a ser un clásico."',
        x: -65,
        y: 870,
        width: 1920,
        fontSize: 52,
        lineHeight: 1,
        bold: "600",
        boldValue: 600,
        italic: true,
        justify: false,
        uppercase: false,
        underline: false,
        list: false,
        listSymbol: "",
        textAlign: "right",
        fontFamily: "Libre Baskerville",
        color: "#ffffff",
        borderWidth: 0,
        borderColor: "#000000",
        shadow: "0 6 16 #000000",
        opacity: 1,
        rotation: 0,
        visible: true,
      },
      instagram: {
        text: "Tormenta de juegos",
        x: -40,
        y: 685,
        width: 1000,
        fontSize: 80,
        lineHeight: 1,
        bold: "600",
        boldValue: 600,
        italic: false,
        justify: false,
        uppercase: false,
        underline: false,
        list: false,
        listSymbol: "",
        textAlign: "right",
        fontFamily: "Libre Baskerville",
        color: "#ffffff",
        borderWidth: 0,
        borderColor: "#000000",
        shadow: "0 6 16 #000000",
        opacity: 1,
        rotation: 0,
        visible: true,
      },
    },
  ],
};
